Added 2 features, locking, branching

diff --git a/runansible b/runansible
--- a/runansible
+++ b/runansible
@@ -13,27 +13,42 @@ PLAYBOOKDIR=playbooks
 UPDATE_ROLES=false
 OLD_ANSIBLE=false
 UPDATE_GIT=false
+IGNORE_LOCK=false
 SPARSE=false
 INVENTORY=""
+DEFAULT_BRANCH=master
 
 # Override any defaults that are set by the user
 test -f $HOME/.runansible.conf && . $HOME/.runansible.conf
 
 usage="Usage: $0 [-p project] [-i inventory] [-s] playbook.yml
 
+    -b branch    Run on specific git branch
+                 When using this option, the script will check out the specified
+                 git branch, run Ansible and then check out $DEFAULT_BRANCH
     -g           Update git checkout before running
+    -l           Ignore locks and allow for multiple instances of $(basename $0)
     -p project   Name of the project to run the playbook from
     -i project   Name of the inventory to use, can be provided multiple times
     -r           Update roles before running playbook
     -R           Update roles before running playbook (compatible with 2.9)
     -s           Make Ansible's output sparse
     -h           This text
+
+By default, this script will attempt to exclusively lock the playbook that is executed.
+This is to prevent multiple runs of the same playbook at once.
 "
 
-while getopts "ghi:p:srR" opt; do
+while getopts "b:glhi:p:srR" opt; do
   case ${opt} in
+    b)
+      BRANCH="$OPTARG"
+      ;;
     g)
       UPDATE_GIT=true
+      ;;
+    l)
+      IGNORE_LOCK=true
       ;;
     p)
       PROJECT="$OPTARG"
@@ -104,4 +119,33 @@ then
   fi
 fi
 
-ansible-playbook $INVENTORY -e ara_playbook_name="'$PROJECT - $PLAYBOOK'" --diff $PLAYBOOKDIR/$PLAYBOOK "$@"
+LOCK_CMD="flock -w 5 -x -E 66 $PLAYBOOKDIR/$PLAYBOOK "
+if $IGNORE_LOCK
+then
+  echo "WARNING: Ignoring locking and starting concurrent run
+
+Current active branch: $(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
+"
+  LOCK_CMD=""
+fi
+
+if [ -n "$BRANCH" ]
+then
+  git checkout $BRANCH
+fi
+
+$LOCK_CMD ansible-playbook $INVENTORY -e ara_playbook_name="'$PROJECT - $PLAYBOOK'" --diff $PLAYBOOKDIR/$PLAYBOOK "$@"
+
+if [ $? -eq 66 ]
+then
+  echo "ERROR: Unable to acquire lock
+  Project:               $PROJECT
+  Playbook:              $PLAYBOOK
+  Current active branch: $(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
+Please try again later..."
+fi
+
+if [ -n "$BRANCH" ]
+then
+  git checkout $DEFAULT_BRANCH
+fi
