Move checking for playbook after git update has been done

diff --git a/runansible b/runansible
--- a/runansible
+++ b/runansible
@@ -105,12 +105,6 @@ fi
 
 cd $PROJECTDIR/$PROJECT
 
-if [ ! -f "$PLAYBOOKDIR/$PLAYBOOK" ]
-then
-  echo "ERROR: Playbook does not exist!"
-  exit 1
-fi
-
 test -f $ANSIBLE_VAULT_PASSWORD_FILE && export ANSIBLE_VAULT_PASSWORD_FILE
 
 # check for update_checkout and use that if it's present
@@ -136,6 +130,12 @@ then
       git pull
     fi
   fi
+fi
+
+if [ ! -f "$PLAYBOOKDIR/$PLAYBOOK" ]
+then
+  echo "ERROR: Playbook does not exist!"
+  exit 1
 fi
 
 if $UPDATE_ROLES
